version: "3.8"

services:
  app:
    container_name: demo
    image: demo
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/profiles
      - SPRING_DATASOURCE_USERNAME=ybyiring
      - SPRING_DATASOURCE_PASSWORD=Ngfin2024!
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Ngfin2024!
      - POSTGRES_USER=ybyiring
      - POSTGRES_DB=profiles


