services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ybyiring
      POSTGRES_PASSWORD: Ngfin2024!
      POSTGRES_DB: profiles
    ports:
      - "5432:5432"
